omrikiei/ktunnel

- cmd/client.go
- cmd/expose.go
- cmd/inject.go
- cmd/root.go
- cmd/server.go
- examples/pycharm-remote-debugging-on-k8s/deployment.yaml
- pkg/client/client.go
- pkg/common/common.go
- pkg/k8s/common.go
- pkg/k8s/exposer.go
- pkg/k8s/injector.go
- pkg/server/server.go
**What this PR does**: This PR fixes the issues found in https://github.com/omrikiei/ktunnel/issues/24, and some struggles I ran into when trying to use this as a library with my own project. The main highlights are:
* Uses `context` for cancellation in both the client and server.
* Uses a single static buffer on the session, and then reads in chunks from each side for TCP listeners instead of a dynamically resized buffer. Right now the limit is around 3MB, which is below the 4MB limit.
* Uses functional args for configuration to allow for easier updates to these interfaces
* Allows the user to pass their own logger, with the default being a logrus logger that uses `ioutil.Discard` as the out.
* Few misc adjustments around handling TCP client connections, closing, and etc.
**What's …
> feat: use static buffer, context for cancellation, and functional arguments

- pkg/k8s/common.go
- pkg/k8s/exposer.go
- pkg/k8s/injector.go
This PR adds:
* a better exposition method for the Service (it's labeled with the same labels than the Pod)
* naming on the Service ports, based on their scheme and port number (tcp-1234, udp-3456).
* actual port exposition on the containers of the Deployment (expose) method. Hence, ports can be directly discovered/used on the Pods if required.
Should also resolve #43
> Enhance Service Discovery for exposed service/pod

- cmd/inject.go
- pkg/k8s/common.go
- pkg/k8s/injector.go
Re: #47
I'm not too familiar with the k8 api, so I don't know if there is a way to get the updated time for the deployment, but the creation time did not appear to be changing when updated. Using the current time seems to achieve the desired effect.
> Use current time when waiting for injector to be ready

- pkg/k8s/common.go
- pkg/k8s/injector.go
HI @omrikiei,
The primary reason for this change is to fix a bug detecting `ProgressDeadlineExceeded`.  I was accidentally checking for that in the Type when it should have been in the Reason.
While I was testing it out (Deployments failing because the v1.3.8 image doesn't exist yet), I noticed some inconsistent behavior that led to a bit of refactoring.
It appears that if you have `maxUnavailable: 1` in your Deployment yaml, it can cause issues where `ProgressDeadlineExceeded` is never raised. I added a warning to notify since it is something that can be handled in the yaml.
The other change was getting the most recent update time from the ManagedFields.  This might have been what we were looking for all along with the original `waitForReady` method, but I didn't investigate to …
> Fix error handling for ProgressDeadlineExceeded

- pkg/k8s/common.go
Fixes https://github.com/omrikiei/ktunnel/issues/57
**Changes:**
Use the default loader rules instead of trying to load file directly.
This is needed if we specify multiple files in KUBE_CONFIG env variable
**Tests:**
Verified ktunnel launches successfully without crashing
> Load the kubeconfig using the DefaultLoader rules

- README.md
- cmd/expose.go
- pkg/k8s/exposer.go
this can useful if user just want use same service ip as it may have configured already in some other deployments/applications to use. 
deleting and recreating service will change ip address for service which may not be desired for few users (for us).
> reusing existing deployment and service for creating tunnel

- pkg/k8s/common.go
Image appears to work fine running as non-root user.
> Add securityContext to make container run as non-root user.

- .krew.yaml
I recently switched to an ARM based MacBook, and noticed that installing ktunnel via krew failed.
This PR should add your existing ARM binaries to the krew index.
---
Unrelated to this PR: You mentioned in #75 that you want to switch to a different container registry. Would you be open to accept a PR to switch to ghcr.io?
> fix: add arm64 binaries to krew manifest bot template

- cmd/expose.go
- docs/ktunnel_expose.md
- pkg/k8s/common.go
- pkg/k8s/exposer.go
Hi!
This PR allows the ktunnel to support any service type when using `expose command`.
Specifically, the ALB only supports `NodePort` or `LoadBalancer` if it uses.
Now I deal with the above problem by updating the service resource using `kubectl edit command`.
Therefore, I would like to optionally set the service type option when using the expose command. 
```bash
ktunnel expose myapp 80:8000 --service-type=NodePort
```
- https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html
- https://pkg.go.dev/k8s.io/api@v0.25.4/core/v1#ServiceSpec
> Add service type option to expose command

- pkg/k8s/common.go
- pkg/k8s/exposer.go
When a deployment is updated (using `--reuse`), and if `waitForReady()` is invoked before k8s actually started to schedule pods, then it will return immediately and eventually fail with:
```
failed parsing session uuid from stream, skipping  error="invalid UUID length: 0" session=
```
Using `watchForReady()` instead ensure that the deployment actually reach a stable state.
> Fix race condition in deployment ready state detection

- pkg/client/client.go
- pkg/common/common.go
Allowing to forward other hosts than `localhost` to Kubernetes.
- `ktunnel expose mynginx 8080:nginx:80` to forward all requests targeted at `mynginx:8080` inside K8s to another host `nginx:80`.
- If no hostname is provided, it uses localhost to preserve the current behaviour.
Tested it in combination with docker-compose to create a reproducable testing environment.
*Dockerfile*:
```Dockerfile
FROM dtzar/helm-kubectl:latest
COPY test/ktunnel /usr/local/bin
```
*docker-compose.yml*:
```yml
version: '3.3'
services:
tunnel: # Creates K8s service mynginx:8080 and forwards all traffic to nginx:80
build: .
volumes:
- /home/xxx/.kube/config:/root/.kube/config:ro
command:
- 'bash'
- '-c'
- 'ktunnel expose mynginx 8080:nginx:80'
nginx: # Runs on Port 80
image: nginx
```
Hi @omrikiei,
I tried my …
> feat: Allowing to forward other hostnames than localhost (#108)

- README.md
- pkg/k8s/exposer.go
This PR simply adds grpc-web to the list of supported schemes for the exposer. grpc-web is on the TCP protocol, so the only difference in the resulting deployment is that the service exposed will have its port name prefixed by grpc-web. This is especially useful using grpc-web with istio as the envoy proxy will know to convert an http request to grpc.
> Add istio/envoy grpc-web support

- cmd/expose.go
- docs/ktunnel_expose.md
- pkg/k8s/common.go
- pkg/k8s/exposer.go
Idea behind this feature is to add ktunnel deployment into existing service.
Matching selector labels and portname of existing service will add ktunnel deployment into it.
> feat: enable setting custom labels and container portname and deployment only mode

- pkg/server/server.go
Upon starting the read loop, immediately send the current session to initiate the connection with the remote end, rather than waiting for the first data packet from the pod.
Fixes #60
> Start the session immediately in the read loop

- cmd/expose.go
- docs/ktunnel_expose.md
- pkg/k8s/common.go
- pkg/k8s/exposer.go
Hello @omrikiei. Thanks for all your work on this project.
I have a Kubernetes application that doesn't support Istio sidecar, but others do. To disable Istio injection for a specific pod, it's necessary to add the annotation `sidecar.istio.io/inject=false`. I wanted to connect the application to a local SigNoz instance to get trace data, but found that `ktunnel` doesn't have a flag to set annotations.
I've prepared a small change to add this capability.
> Add a flag to set deployment annotations

- cmd/expose.go
- cmd/inject.go
- pkg/k8s/common.go
Concerning https://github.com/omrikiei/ktunnel/issues/129
**Problem**
The `ktunnel expose` command encounters a deadlock, ignoring SIGINTs, and requiring a manual process kill.
**Root Cause**
In the k8s.PortForward function, the fwdWaitGroup counter is not decremented when readyChan is not closed (see [common.go#L281](https://github.com/omrikiei/ktunnel/blob/master/pkg/k8s/common.go#L281)). This results in an unresolved `wg.Wait()` in the expose command (see [expose.go#L137](https://github.com/omrikiei/ktunnel/blob/master/cmd/expose.go#L137)).
**Solution**
To maintain the current function signature of k8s.PortForward, the function should defer its return until all ready signals are received or an error occurs on one of the forwarders.
If changing the function signature is permissible, …
> fix: resolve shutdown deadlock on port forwarding when port is already in use

- cmd/expose.go
- cmd/inject.go
- pkg/k8s/injector.go
This PR makes it so the k8s package log level is set to debug when passing --verbose to the expose or inject commands. I found this helpful for debugging and thought it made sense to contribute back in case it helps someone else!
before:
```
INFO[0002] Exposed service's cluster ip is: xxx
INFO[0002] ProgressDeadlineInSeconds is currently 600s. It may take this long to detect a deployment failure. 
INFO[0002] waiting for deployment to be ready           
INFO[0005] deployment "xxx" successfully rolled out 
INFO[0005] port forwarding to xxx/portforward 
INFO[0005] Waiting for port forward to finish           
INFO[0006] Forwarding from 127.0.0.1:28688 -> 28688
Forwarding from [::1]:28688 -> 28688 
INFO[2024-06-21 16:42:00.608] starting tcp tunnel from source 8443 to target localhost:8443 …
```
> fix: set k8s log level to debug when --verbose is set

- pkg/k8s/injector_test.go
This PR improves the test coverage of the Kubernetes-related functionality by:
- Adding comprehensive tests for the `injectToDeployment` function
- Adding tests for the `removeFromSpec` function
- Covering edge cases and error conditions
- Improving test structure and mocking
The changes focus on testing core functionality while maintaining the existing test patterns and structure.
> Improve Kubernetes test coverage

- pkg/k8s/common_test.go
- pkg/k8s/injector_test.go
This PR enhances the test coverage of the Kubernetes-related functionality by:
- Adding comprehensive tests for the `injectToDeployment` function
- Adding tests for the `removeFromSpec` function
- Adding tests for `newContainer` with various configurations
- Adding tests for `newDeployment` and `newService` functions
- Adding tests for `deploymentStatus` function
- Adding tests for `ByCreationTime` sorting
The changes focus on testing core functionality while maintaining the existing test patterns and structure.
> Enhance test coverage for Kubernetes functionality

- pkg/k8s/common.go
This PR fixes several race conditions:
- Replace sync.Once with proper mutex protection
- Add thread-safe access to global variables
- Add proper locking around client operations
- Add proper locking around kubeconfig access
- Add proper locking around verbose flag
These changes should resolve the data race issues in the tests.
> Fix race conditions
